Support SFT
SIVIRA/sample-contracts pull request #25
Opened 2024-06-21 09:14 UTC by taxio

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +        string memory uri_,
OpenZeppelin の `ERC1155` が引数に `uri` を取るのなーなんだかなーしょうがないですな。

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
token URI の freeze が実装されてないですね。

ref. https://sivira.slack.com/archives/C05HRGQAAMP/p1718880541420979

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +            InsufficientHolding(holder_, tokenID_)
エラー名は関数名に引っ張られずに素直に `InsufficientBalance` でよきかなと思いました。

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +        internal _holdingStartedAts;
OpenZeppelin の `ERC1155` の `_balances` は token ID の方が上位のキーになってる模様。これと揃えましょうか。

ref. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3f8b760ad9d0431f33e8303658ccbdcc1610f24/contracts/token/ERC1155/ERC1155.sol#L23C5-L23C82

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/SampleSFT.sol
> +        string memory uri_,
これ実質使わないと思うので、`SampleSFT` ではコンストラクタの引数として指定できるようにせず、空文字列を固定で `BaseSFT` に渡すようにしましょうか。

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +                    _holdingStartedAts[to][tokenID] = block.timestamp;
`_holdingThresholds[tokenID]` って未設定の場合に 0 が返ると思うんですが、そうなると未設定でもこれが実行されて storage を使っちゃうことになるような？

上記の通りなら、ループ処理の頭で `_holdingThresholds[tokenID] == 0` の場合はスキップするとかかな。

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> Pausable は BaseSFT の中でどれくらい散りばめるか？

一旦今の状態（`BaseSFT` 側には散りばめない）で大丈夫です 🆗

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> BaseNFT に TokenType range の setter が無いので、BaseSFT にも TokenID range の setter を用意してないが良いか？

一旦 NFT の方と挙動を揃えておきたいので用意しなくて大丈夫です 🆗 

が、ERC1155 は token ID range 必須ではあるので、近いうちに base の方に setter を実装するで揃えた方がよきかもですなあ。

2024-06-22 12:42 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +    ) external {
`onlyOwner` modifier が必要すね。

2024-06-26 05:10 UTC, taxio commented on contracts/BaseSFT.sol
> +    ) external {
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/18145215586aa5adee970285e54565ad1ea5c001

2024-06-26 05:10 UTC, taxio commented on contracts/BaseSFT.sol
> +            InsufficientHolding(holder_, tokenID_)
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/18145215586aa5adee970285e54565ad1ea5c001

2024-06-26 05:10 UTC, taxio commented on contracts/BaseSFT.sol
> +    function _requireTokenTypeRangeNotFrozen() internal view {
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/18145215586aa5adee970285e54565ad1ea5c001

2024-06-26 05:10 UTC, taxio commented on contracts/BaseSFT.sol
> +    function freezeTokenTypeRange() external onlyOwner {
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/18145215586aa5adee970285e54565ad1ea5c001

2024-06-26 05:19 UTC, taxio commented on contracts/SampleSFT.sol
> +        string memory uri_,
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/5bdc9f72ec95c426bc1d59de40a53b672c18718a

2024-06-26 05:19 UTC, taxio commented on contracts/BaseSFT.sol
> +                    _holdingStartedAts[to][tokenID] = block.timestamp;
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/3adaa666b75f91a392ea6260f644b02d08e77a74

2024-06-26 05:19 UTC, taxio commented on contracts/BaseSFT.sol
> +        internal _holdingStartedAts;
修正 https://github.com/SIVIRA/sample-contracts/pull/25/commits/3adaa666b75f91a392ea6260f644b02d08e77a74

2024-06-26 05:22 UTC, taxio commented on contracts/BaseSFT.sol
> token URI の freeze が実装されてないですね。

実装した気になってたんですが違いました？
https://github.com/SIVIRA/sample-contracts/blob/3adaa666b75f91a392ea6260f644b02d08e77a74/contracts/BaseSFT.sol#L17
https://github.com/SIVIRA/sample-contracts/blob/3adaa666b75f91a392ea6260f644b02d08e77a74/contracts/BaseSFT.sol#L45
https://github.com/SIVIRA/sample-contracts/blob/3adaa666b75f91a392ea6260f644b02d08e77a74/contracts/BaseSFT.sol#L260-L262
https://github.com/SIVIRA/sample-contracts/blob/3adaa666b75f91a392ea6260f644b02d08e77a74/contracts/BaseSFT.sol#L162-L167

2024-06-26 06:52 UTC, m0t0k1ch1 requested changes

2024-06-26 06:52 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
freeze する関数だけ見当たらないような 👀

2024-06-26 07:58 UTC, taxio commented on contracts/BaseSFT.sol
あーーー、目が節穴でした。

2024-06-26 08:00 UTC, taxio commented on contracts/BaseSFT.sol
追加しました https://github.com/SIVIRA/sample-contracts/pull/25/commits/88e4ac55585be74307b2b96a3666fa0ecbba3a52

2024-06-26 08:12 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
`BaseNFT` と同様、以下のイベントを定義して吐いておいてほしいです🙏

``` solidity

```

ref. https://docs.opensea.io/docs/metadata-standards#freezing-metadata

2024-06-26 08:18 UTC, taxio commented on contracts/BaseSFT.sol
追加しました https://github.com/SIVIRA/sample-contracts/pull/25/commits/af5ada6adbabdf1d671c4140725f1b83dcc5f83e

2024-06-27 08:27 UTC, m0t0k1ch1 approved these changes
🆗

2024-06-27 08:30 UTC, merged