fix: token registration
SIVIRA/sample-contracts pull request #28
Opened 2024-07-03 04:01 UTC by taxio

HoldingThreshold は最初に登録したら変えれないようにしたい。

`addToken` で Token を追加していく形で登録できるようにした。
追加時に URI と HoldingThreshold が指定できる。
URI は後から `setTokenURI` で変更可能。

2024-07-03 07:17 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +        _maxTokenID++;
`tokenID` も引数で指定できるようにしましょうか。

2024-07-03 07:22 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +        _maxTokenID++;
となると、追加された `tokenID` を管理する `mapping(uint256 tokenID => bool)` と、その getter みたいな関数 `isTokenIDAdded` みたいな関数も追加することになるかな。

2024-07-03 07:46 UTC, taxio commented on contracts/BaseSFT.sol
> +        _maxTokenID++;
分かりました 🙆‍♂️

2024-07-03 08:39 UTC, taxio commented on contracts/BaseSFT.sol
> +        _maxTokenID++;
修正 https://github.com/SIVIRA/sample-contracts/pull/28/commits/16c09108ef942675bb1ccc10d16c0b444ff28706

2024-07-03 16:39 UTC, m0t0k1ch1 requested changes

2024-07-03 16:39 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +    mapping(uint256 tokenID => bool) internal _tokenRegistered;
他の mapping と命名を揃えるとなると以下がベターかしら。

``` solidity
mapping(uint256 tokenID => bool isTokenRegistered) internal _isTokenRegistereds;
```

2024-07-03 16:39 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +    mapping(uint256 tokenID => bool) internal _tokenRegistered;
と、これの getter として `isTokenRegistered` 関数を生やしておいてほしいです。

ref. https://github.com/SIVIRA/sample-contracts/pull/28#discussion_r1663657743

2024-07-04 06:58 UTC, m0t0k1ch1 approved these changes
コメントした点を修正してもらったら merge してもらって大丈夫です 🆗

2024-07-04 06:58 UTC, m0t0k1ch1 commented on contracts/BaseSFT.sol
> +    mapping(uint256 tokenID => bool) internal _isTokenRegistered;
めちゃ細かいですが、他の mapping と揃えてケツに s つけておいてもらえればと🙏

https://github.com/SIVIRA/sample-contracts/pull/28#discussion_r1664472345

2024-07-04 10:18 UTC, taxio commented on contracts/BaseSFT.sol
> +    mapping(uint256 tokenID => bool) internal _isTokenRegistered;
修正 https://github.com/SIVIRA/sample-contracts/pull/28/commits/828700e1130aa0a55439fb7692864086f24d747c

2024-07-04 10:19 UTC, merged