Support SBSFT
SIVIRA/sample-contracts pull request #29
Opened 2024-07-03 09:08 UTC by taxio

2024-07-07 09:44 UTC, m0t0k1ch1 commented
ローカルで `BaseSFT` との diff を眺めたかったので main branch を merge。

https://github.com/SIVIRA/sample-contracts/pull/29/commits/eec87833af4ea195271d444467799b50c7e08a67

2024-07-07 11:44 UTC, m0t0k1ch1 requested changes

2024-07-07 11:44 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +            _holdingThresholds[tokenID_] > 0 &&
`BaseSFT` の方も含め、この条件は不要になったかな。

2024-07-07 11:44 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +            if (to != address(0)) {
`from` と `to` がゼロアドレスじゃないことは確定なので、このチェックは不要かな。

2024-07-07 11:44 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +            if (from != address(0)) {
上記コメントと同様。

2024-07-07 11:44 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +                    balanceOf(to, tokenID) < _holdingThresholds[tokenID]
`BaseSFT` の方も含め、この条件が成立することってありますっけ？

2024-07-09 05:45 UTC, taxio commented on contracts/BaseSBSFT.sol
> +            if (to != address(0)) {
`from` は mint 時にゼロアドレスになります。
`to` は burn 時にゼロアドレスになります。
一応 SBNFT が burn を想定していたので、こちらもそれに追従してます。
https://github.com/SIVIRA/sample-contracts/blob/3128b80be8d9ad9881a676d4f30ca699592915d3/contracts/BaseSBNFT.sol#L237-L266

2024-07-09 05:48 UTC, taxio commented on contracts/BaseSBSFT.sol
> +                    balanceOf(to, tokenID) < _holdingThresholds[tokenID]
以下のシチュエーションで条件が成立します。

BaseSFT:
* threshold=2, balance=0 の状態で1枚だけ mint した
* threshold=1, balance=1 の状態で1枚 transfer or burn した

BaseSBSFT:
* threshold=1, balance=1 の状態で1枚 burn した

2024-07-09 05:53 UTC, taxio commented on contracts/BaseSBSFT.sol
> +            _holdingThresholds[tokenID_] > 0 &&
修正 https://github.com/SIVIRA/sample-contracts/pull/29/commits/03b2e08495aac190bb87140f6758f3fb6daea5b1

2024-07-09 06:54 UTC, m0t0k1ch1 approved these changes

2024-07-09 06:54 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +            if (to != address(0)) {
あ、なんか頭悪いこと書いてましたね申し訳ない...🙏

2024-07-09 06:54 UTC, m0t0k1ch1 commented on contracts/BaseSBSFT.sol
> +                    balanceOf(to, tokenID) < _holdingThresholds[tokenID]
どうやら burn が頭になかったようです🙏
なんか今回はすっとぼけレビューかましてますな...

2024-07-09 09:36 UTC, merged