Support FT
SIVIRA/sample-contracts pull request #31
Opened 2024-07-11 13:55 UTC by taxio

* FT を追加
* SFT に cap を追加

TODO
- [ ] FT のテストを追加
- [ ] SFT に cap のテストを追加
- [ ] SBSFT に cap のテストを追加

2024-07-14 14:17 UTC, m0t0k1ch1 requested changes

2024-07-14 14:17 UTC, m0t0k1ch1 commented on contracts/BaseFT.sol
> +        }
SFT とできるだけ近しい実装にしたいので `_mint` を override してそっちでチェックしましょうか。if 文も書かなくてよくなりますし。

2024-07-14 14:17 UTC, m0t0k1ch1 commented on contracts/BaseFT.sol
> +                _holdingStartedAts[from_] = 0;
SFT の方もですが、`_holdingStartedAts[from_] > 0` の条件を足すと storage を節約できる...？初期状態と 0 を保存した状態って変わらないんでしたっけ？ちょっと確認してみてほしいです🙏

2024-07-16 06:38 UTC, taxio commented on contracts/BaseFT.sol
> +                _holdingStartedAts[from_] = 0;
確かに holdingThreshold を下回っているときの transfer で節約できますね。
修正します！

2024-07-16 06:44 UTC, taxio commented on contracts/BaseFT.sol
> +                _holdingStartedAts[from_] = 0;
FT, SFT, SBSFT の対応完了 https://github.com/SIVIRA/sample-contracts/pull/31/commits/ed26a5f0fd77fde6e60ea33b79bd841b6a641e34

2024-07-16 07:26 UTC, m0t0k1ch1 commented on contracts/BaseFT.sol
> +        }
あらーそうなのか... では一旦このままでいきましょう。

OpenZeppelin v5 の設計はあんまり好きくないなあ。

2024-07-16 07:27 UTC, m0t0k1ch1 approved these changes
:ok:

2024-07-16 07:30 UTC, merged